//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Application3
{
    using System;
    using System.Collections.Generic;
    
    public partial class basic_infos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public basic_infos()
        {
            this.educational_infos = new HashSet<educational_infos>();
            this.professional_Infos = new HashSet<professional_Infos>();
            this.projects = new HashSet<project>();
        }
    
        public string user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string location { get; set; }
        public string email { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<educational_infos> educational_infos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<professional_Infos> professional_Infos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
    }
}
