//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Application3
{
    using System;
    using System.Collections.Generic;
    
    public partial class educational_infos
    {
        public int edu_id { get; set; }
        public string uni_name { get; set; }
        public string pass_year { get; set; }
        public string degree_name { get; set; }
        public string user_id { get; set; }
    
        public virtual basic_infos basic_infos { get; set; }
    }
}
