//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Application3
{
    using System;
    using System.Collections.Generic;
    
    public partial class professional_Infos
    {
        public int skill_id { get; set; }
        public string occupation_type { get; set; }
        public string company_type { get; set; }
        public string position_type { get; set; }
        public string user_id { get; set; }
        public Nullable<int> no_of_projects { get; set; }
    
        public virtual basic_infos basic_infos { get; set; }
    }
}
